### ISSUE TITLE
Destination folder does not exist!

### ISSUE THREAD

**Issue by EZfixman** [ArwynFr/arma3sync-docker#2]
After creating a new repository I tried to sync it via the SYNC command

```
Please enter a command = sync

Synchronize with repository
Enter repository name: reponame
Loading repositories...
Enter destination folder path: home/user/gameservers/arma3server
Destination folder does not exists!
```

**Comment by ArwynFr** [comment]
Hi EZfixman,

I strongly recommend you use absolute paths, otherwise Arma3Sync will probably consider the path relative to its current working directory. Looks like you meant `/home/user/gameservers/arma3server` for your destination folder (mind the leading slash).

Arma3Sync will not create the folder if it does not exist. This is Arma3Sync behavior, if you want it to create the folder instead, you may ask major_shepard to update the program. Note that mounting a volume (with `--volume mods:/home/user/gameservers/arma3server`) will create the directory even if the volume is empy.

**Comment by EZfixman** [comment]
Danke Schön
